name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 1.0.0-rc.1
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  notus: ^1.0.0-rc.1
  quill_delta: ^3.0.0-nullsafety.1
  html: ^0.15.0

dev_dependencies:
  test:
